<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="7"
           failures="2"
           errors="0"
           skipped="0"
           time="0.008">
  <properties />
            <testcase name="ACK_16" time="0.000" classname="Wire_Scenario.RunJOBWireInstructionsProcessor">
                <failure type="java.lang.AssertionError"
                  message="expected [2] but found [3]"
              >
<![CDATA[java.lang.AssertionError: expected [2] but found [3]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  Wire_Scenario.RunJOBWireInstructionsProcessor.ACK_16(RunJOBWireInstructionsProcessor.java:45)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:776)
  org.testng.TestRunner.run(TestRunner.java:634)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
  org.testng.SuiteRunner.run(SuiteRunner.java:334)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
  org.testng.TestNG.runSuites(TestNG.java:1161)
  org.testng.TestNG.run(TestNG.java:1129)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
            <testcase name="TC_07" time="0.005" classname="Wire_Scenario.RunJOBWireInstructionsProcessor">
                <failure type="java.lang.AssertionError"
                  message="expected [Hello] but found [Hello World]"
              >
<![CDATA[java.lang.AssertionError: expected [Hello] but found [Hello World]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  Wire_Scenario.RunJOBWireInstructionsProcessor.TC_07(RunJOBWireInstructionsProcessor.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:776)
  org.testng.TestRunner.run(TestRunner.java:634)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
  org.testng.SuiteRunner.run(SuiteRunner.java:334)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
  org.testng.TestNG.runSuites(TestNG.java:1161)
  org.testng.TestNG.run(TestNG.java:1129)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="ACK_15" time="0.000" classname="Wire_Scenario.RunJOBWireInstructionsProcessor" />
                <testcase name="TC_08" time="0.001" classname="Wire_Scenario.RunJOBWireInstructionsProcessor" />
                <testcase name="TC_09" time="0.001" classname="Wire_Scenario.RunJOBWireInstructionsProcessor" />
                <testcase name="ACK_17" time="0.001" classname="Wire_Scenario.RunJOBWireInstructionsProcessor" />
                <testcase name="ACK_18" time="0.000" classname="Wire_Scenario.RunJOBWireInstructionsProcessor" />
      
</testsuite>
